package SqlQueries;

public class Queries {

	public static String AddReminderQuery = "SELECT STB.MACADDRESS, DTV.EXTERNALID, SFS.SCHEDULETRAILID FROM subscribers s,customer_na@TO_UUSD cna,SETTOPBOXES STB,subscriberpackages sp, packageitems pi,dtvchannels dtv,schedulefilespec sfs WHERE S.ID = CNA.SUBSCRIBER_ID AND S.ID = STB.ASSIGNEDTOSUBSCRIBERID AND SP.SUBSCRIBERID = S.ID AND SP.PACKAGEID = PI.PACKAGEID AND PI.ITEMID = DTV.ID AND DTV.CHANNELREFERENCENO = SFS.CHANNELREFERENCENUMBER AND S.STATUS = 'Active' AND S.STATUSCODE = 'A' AND STB.STATUS='Assigned'  AND STB.RECORDSTATUSCODE='A' AND rownum < 100 order by SFS.SCHEDULETRAILID desc";
	public static String getReminderQuery = "SELECT REMINDERID,MACADDRESS,REMINDERTYPE,REMINDERMINUTESBEFORESTART,REMINDERCREATIONDATETIME FROM SETTOPBOXREMINDERS WHERE REMINDERCREATIONDATETIME IS NOT NULL ORDER BY REMINDERCREATIONDATETIME DESC";
	public static String deleteReminderQuery="delete from SETTOPBOXREMINDERS  WHERE SETTOPBOXREMINDERS.REMINDERCREATIONDATETIME IS NOT NULL and SETTOPBOXREMINDERS.REMINDERCREATIONDATETIME>sysdate";
	public static String macEquipmentQuery="select stb.MACADDRESS, stb.EQUIPMENTID from settopboxes stb, subscribers s where s.id = STB.ASSIGNEDTOSUBSCRIBERID and S.STATUS = 'Active' and S.STATUSCODE = 'A' and RECORDSTATUSCODE = 'A'  and stb.STATUS = 'Assigned' and STB.EQUIPMENTID not in (select equipmentid from SETTOPBOXPROPERTIES) and ASSIGNEDTOSUBSCRIBERID is not null";
	
}
