//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.09 at 11:53:27 AM IST 
//


package xsdTojava;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SetSTBPropertiesDoc">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Properties" type="{}T_STBProperties"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "setSTBPropertiesDoc"
})
@XmlRootElement(name = "BTA")
public class BTA {

    @XmlElement(name = "SetSTBPropertiesDoc", required = true)
    protected BTA.SetSTBPropertiesDoc setSTBPropertiesDoc;

    /**
     * Gets the value of the setSTBPropertiesDoc property.
     * 
     * @return
     *     possible object is
     *     {@link BTA.SetSTBPropertiesDoc }
     *     
     */
    public BTA.SetSTBPropertiesDoc getSetSTBPropertiesDoc() {
        return setSTBPropertiesDoc;
    }

    /**
     * Sets the value of the setSTBPropertiesDoc property.
     * 
     * @param value
     *     allowed object is
     *     {@link BTA.SetSTBPropertiesDoc }
     *     
     */
    public void setSetSTBPropertiesDoc(BTA.SetSTBPropertiesDoc value) {
        this.setSTBPropertiesDoc = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Properties" type="{}T_STBProperties"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "properties"
    })
    public static class SetSTBPropertiesDoc {

        @XmlElement(name = "Properties", required = true)
        protected TSTBProperties properties;

        /**
         * Gets the value of the properties property.
         * 
         * @return
         *     possible object is
         *     {@link TSTBProperties }
         *     
         */
        public TSTBProperties getProperties() {
            return properties;
        }

        /**
         * Sets the value of the properties property.
         * 
         * @param value
         *     allowed object is
         *     {@link TSTBProperties }
         *     
         */
        public void setProperties(TSTBProperties value) {
            this.properties = value;
        }

    }

}
