//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.09 at 11:53:53 AM IST 
//


package xsdTojava;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the resources package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Value_QNAME = new QName("", "Value");
    private final static QName _Name_QNAME = new QName("", "Name");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: resources
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TSTBProperties }
     * 
     */
    public TSTBProperties createTSTBProperties() {
        return new TSTBProperties();
    }

    /**
     * Create an instance of {@link TSTBPropertyNames }
     * 
     */
    public TSTBPropertyNames createTSTBPropertyNames() {
        return new TSTBPropertyNames();
    }

    /**
     * Create an instance of {@link TSTBProperties.Property }
     * 
     */
    public TSTBProperties.Property createTSTBPropertiesProperty() {
        return new TSTBProperties.Property();
    }

    /**
     * Create an instance of {@link TSTBPropertyNames.Property }
     * 
     */
    public TSTBPropertyNames.Property createTSTBPropertyNamesProperty() {
        return new TSTBPropertyNames.Property();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Value")
    public JAXBElement<String> createValue(String value) {
        return new JAXBElement<String>(_Value_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Name")
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
    }

}
